# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yhLdMtD4lFDNZkFV4PBc-3iw0Djc3q__
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df=pd.read_csv("Amazon.csv")
print(df)

print(df.head())

print(df.shape)

print(df.info)

df.dropna(inplace=True)
print(df.shape)

print(df.isnull().sum())

# check duplicate rows
print("Number of duplicate rows:", df.duplicated())

# display duplicate rows
duplicates = df[df.duplicated()]
print(duplicates)

total_sales=df["TotalAmount"].sum()
print("Total sales:",total_sales)

total_sales=df["TotalAmount"].max()
print("maximum sales:",total_sales)

total_sales=df["TotalAmount"].min()
print("minimum sales:",total_sales)

total_sales=df.groupby("ProductName")["TotalAmount"].mean()
print("average sales:",total_sales)

total_sales=df["TotalAmount"].median()
print("median:",total_sales)

total_transactions = df["ProductName"].count()
print("Total number of transactions:", total_transactions)

total_sales=df.groupby("ProductName")["TotalAmount"].sum()
print("Total sales:,",total_sales)

product_total_sales = df.groupby("ProductName")["TotalAmount"].sum()
highest_product = product_total_sales.idxmax()
highest_sales = product_total_sales.max()

print("Product with highest total sales:", highest_product)
print("Highest total sales amount:", highest_sales)

product_total_sales = df.groupby("ProductName")["TotalAmount"].sum()
lowest_product = product_total_sales.idxmin()
lowest_sales = product_total_sales.min()

print("Product with lowest total sales:", lowest_product)
print("lowest total sales amount:", lowest_sales)

number_of_transactions=df["ProductName"].value_counts()
print("number of transactions:",number_of_transactions)

top_selling_products=df.groupby("ProductName")["TotalAmount"].sum()
top_selling_products=top_selling_products.sort_values(ascending=False).head(5)
print(top_selling_products)

least_selling_products=df.groupby("ProductName")["TotalAmount"].sum()
least_selling_products=least_selling_products.sort_values(ascending=True).head(10)
print(least_selling_products)

unique_products=df["PaymentMethod"].unique()
print(unique_products)

transaction_type=df["PaymentMethod"].value_counts()
print(transaction_type)

total_sales=df.groupby("PaymentMethod")["TotalAmount"].sum()
print(total_sales)

payment_method=df["PaymentMethod"].mode()[0]
print(payment_method)

total_online_payments=df[df["PaymentMethod"]=="UPI"]
print(total_online_payments)

total_online_payments=df[df["PaymentMethod"]=="UPI"].shape[0]
print(total_online_payments)

toatl_offline_payments=df[df["PaymentMethod"]=="Cash on Delivery"]
print(toatl_offline_payments)

toatl_offline_payments=df[df["PaymentMethod"]=="Cash on Delivery"].shape[0]
print(toatl_offline_payments)

percentage_of_online_payments=total_online_payments/df.shape[0]*100
print(percentage_of_online_payments)